version: '3.9'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume:/data/db

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - '8080:8080'

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '80:80'

volumes:
  mongo-volume:
