version: '3.9'

services:
  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - '27017:27017'
    volumes:
      - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=user
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=123
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=123
    ports:
      - '8081:8081'
    depends_on:
      - mongo

  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    depends_on:
      - mongo
    # volumes:
    #   - ./backend:/app
    ports:
      - '8000:8000'

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - '80:80'

volumes:
  mongo-volume:
